apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-assignment-2-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-assignment-2-app
  template:
    metadata:
      labels:
        app: devops-assignment-2-app
    spec:
      containers:
      - name: flask-app
        image: nitheeshabr/devops-assignment-2-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
